### ISSUE TITLE
Use red logo instead of black

### ISSUE THREAD

**Issue by mariojankovic** [RedHatter/svelte-devtools#5]
Hey there, awesome work with the dev tools. Been using it on sapper for a while.

Any chance you could switch the black logo for the (official) red one? Or the green one from sapper for all I care. I can even do a MR and help change the colors if that helps?

![i4XALF8](https://user-images.githubusercontent.com/3466800/65267604-a45f0e80-db15-11e9-9017-9da243fd3015.png)

Cheers.

**Comment by RedHatter** [comment]
The Svelte icon should match the rest of the devtool tabs icons. The issue here is that dark mode is not currently supported. See https://discourse.mozilla.org/t/devtools-panel-dark-mode/45341

I'm considering adding a dark mode toggle to svelte-devtools itself. It wouldn't automatically match the devtools settings but that's not *that* big of a deal.

**Comment by mariojankovic** [comment]
I see. The workaround sounds good though. I guess it applies a dark theme altogether? Even with syntax.

**Comment by RedHatter** [comment]
Any feedback on the dark mode colors welcome.
